### ISSUE TITLE
[xcodeproj] Header search paths can point to paths which are never created

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [bazel-ios/rules_ios#322]
Hello there,

I have been testing the `xcodeproj` rule in our codebase and seeing invalid paths in `HEADER_SEARCH_PATHS`, in one of our targets I am seeing this:
<img width="707" alt="Screen Shot 2021-10-03 at 8 35 04 PM" src="https://user-images.githubusercontent.com/56700854/135789294-f4ffa6b8-29d6-4180-af44-4369ce007c6e.png">

This path is never created after building/running or testing. How can I go about figuring out why this path was selected? I do see valid paths for other entires in `FRAMEWOR_SEARCH_PATHS`

**Comment by tinder-maxwellelliott** [comment]
Even with VFS enabled, I can still get paths that do not exist on my system

<img width="1006" alt="Screen Shot 2021-10-04 at 11 40 33 AM" src="https://user-images.githubusercontent.com/56700854/135906230-70206e30-4897-4f88-9c05-4db901d4dd90.png">

**Comment by jerrymarino** [comment]
@tinder-maxwellelliott are you setting `apple.virtualize_frameworks` for both the project and the build? These should be aligned because it won't work. It sounds like they aren't aligned because the project is expecting files that aren't produced by the build.

If you checkout this like of code, you'll find that we _only_ set `OTHER_SWIFT_FLAGS` when `apple.virtualize_frameworks` is enabled:
https://github.com/bazel-ios/rules_ios/blob/master/rules/xcodeproj.bzl#L681

Please LMK if this fixes it for you: I believe the original behavior should still work if you don't set `apple.virtualize_frameworks`  on both the project and the build

**Comment by thiagohmcruz** [comment]
> > @tinder-maxwellelliott are you setting `apple.virtualize_frameworks` for both the project and the build? These should be aligned because the project expects files to be produced by the build
> > If you checkout this like of code, you'll find that we _only_ set `OTHER_SWIFT_FLAGS` when `apple.virtualize_frameworks` is enabled: https://github.com/bazel-ios/rules_ios/blob/master/rules/xcodeproj.bzl#L681
> > Please LMK if this fixes it for you: I believe the original behavior should still work if you don't set `apple.virtualize_frameworks` on both the project and the build
> 
> Okay we are now fully using VFS, thanks for that Jerry. I am still somehow getting old paths in my LLDB logs, should I mark my `xccodeproj` rule with the tag `local`? Trying to figure out where these old paths are coming from
> 
> If I go into `bazel-out` and update the path to the correct one for the current configuration, it seems to be working okay

Could it be that the old paths are coming from some cache in DerivedData cc @jerrymarino?

**Comment by tinder-maxwellelliott** [comment]
This can also come from virtual framework paths not existing as well, something like this

```
 SwiftASTContext("someapp")::GetASTContext() -- failed to initialize ClangImporter: warning: argument unused during compilation: '-Xcc'
error: virtual filesystem overlay file '/Users/maxwellelliott/someapp/someapp_ios/Projects/someapp/../../bazel-out/ios-x86_64-min12.0-applebin_ios-ios_x86_64-dbg-ST-e32b3366c2e3/bin/Projects/someapp/someapp_swift_vfs.yaml' not found
error: virtual filesystem overlay file '/Users/maxwellelliott/someapp/someapp_ios/Projects/someapp/../../bazel-out/ios-x86_64-min12.0-applebin_ios-ios_x86_64-dbg-ST-e32b3366c2e3/bin/Projects/someapp/someapp_swift_vfs.yaml' not found
```

**Comment by jerrymarino** [comment]
@tinder-maxwellelliott that's great to hear!

>...
If I go into bazel-out and update the path to the correct one for the current configuration, it seems to be working okay

When you get those errors I assume you have done a build already? I was also wondering if you were able to repro this on the examples we've got by any chance..

Other than that, there is likely one possible explanation of why the build outputs aren't correctly loading into the project. That is, you've got a different _configuration_ of the inputs to the project and app build outputs. One design problem with rules_ios 's Xcodegen rule is that it must have the same configuration, otherwise, the Xcode project doesn't match the build. We should have a take on this soon and to allow building on device and sims in the same project.

What are the options you're building the project with and then the options you're building the app with? They must be aligned:


```
1057         # Important! The `Debug` is being used to conditionally pass
1058         # flags to LLDB, so if this behaviour ever changes that needs
1059         # to be considered otherwise debugging swift files will stop working
1060         #
1061         # See the logic around setting the `-D DEBUG` flag in
1062         # https://github.com/bazel-ios/rules_ios/blob/master/tools/xcodeproj_shims/installers/lldb-settings.sh
1063         "configs": attr.string_list(mandatory = False, default = [], doc = """
1064         List of bazel configs present in the .bazelrc file that can be used to build targets.
1065
1066         A Xcode build configuration will be created for each entry and a '--config=$CONFIGURATION' will
1067         be appended to the underlying bazel invocation. Effectively allowing the configs in the .bazelrc file
1068         to control how Xcode builds each build configuration.
````


The summary of the issue Xcode is looking for this 
```
ios-x86_64-min12.0-applebin_ios-ios_x86_64-dbg-ST-e32b3366c2e3/bin/Projects/someapp/someapp_swift_vfs.yaml'
```
But your build is not producing that. If you pass an array of `configs`, just make sure that they are identical. That means you invoke  `bazel --config debug run MyXcodeproj`

**Comment by tinder-maxwellelliott** [comment]
> @tinder-maxwellelliott that's great to hear!
> 
> > ...
> > If I go into bazel-out and update the path to the correct one for the current configuration, it seems to be working okay
> 
> When you get those errors I assume you have done a build already? I was also wondering if you were able to repro this on the examples we've got by any chance..
> 
> Other than that, there is likely one possible explanation of why the build outputs aren't correctly loading into the project. That is, you've got a different _configuration_ of the inputs to the project and app build outputs. One design problem with rules_ios 's Xcodegen rule is that it must have the same configuration, otherwise, the Xcode project doesn't match the build. We should have a take on this soon and to allow building on device and sims in the same project.
> 
> What are the options you're building the project with and then the options you're building the app with? They must be aligned:
> 
> ```
> 1057         # Important! The `Debug` is being used to conditionally pass
> 1058         # flags to LLDB, so if this behaviour ever changes that needs
> 1059         # to be considered otherwise debugging swift files will stop working
> 1060         #
> 1061         # See the logic around setting the `-D DEBUG` flag in
> 1062         # https://github.com/bazel-ios/rules_ios/blob/master/tools/xcodeproj_shims/installers/lldb-settings.sh
> 1063         "configs": attr.string_list(mandatory = False, default = [], doc = """
> 1064         List of bazel configs present in the .bazelrc file that can be used to build targets.
> 1065
> 1066         A Xcode build configuration will be created for each entry and a '--config=$CONFIGURATION' will
> 1067         be appended to the underlying bazel invocation. Effectively allowing the configs in the .bazelrc file
> 1068         to control how Xcode builds each build configuration.
> ```
> 
> The summary of the issue Xcode is looking for this
> 
> ```
> ios-x86_64-min12.0-applebin_ios-ios_x86_64-dbg-ST-e32b3366c2e3/bin/Projects/someapp/someapp_swift_vfs.yaml'
> ```
> 
> But your build is not producing that. If you pass an array of `configs`, just make sure that they are identical. That means you invoke `bazel --config debug run MyXcodeproj`

Thank you for this great explanation! I do have some important flags set in `additional_bazel_build_options` that are pretty important to the overall build. I will try to move those out into our general bazelrc and see if that remedies the issue

Thanks again
