### ISSUE TITLE
IDE error integrations do not work with Xcode 13+

### ISSUE THREAD

**Issue by erikkerber** [bazel-ios/rules_ios#360]
Xcode 13/Swift 5.5 introduced a regression where, when VFS overlays are used, error outputs have absolute paths instead of relative paths. This breaks the output processing done via regex in `output-processor.rb`

The end result is that build errors do not show up in the Xcode IDE text editor inline with the location of the error.

**Comment by jerrymarino** [comment]
Thanks for the report @erikkerber! I agree with updating the `output-processor.rb` is a good way to handle it - similar to this: https://github.com/tinyspeck/rules_ios/pull/10/files

Since the build runs relative to that workspace directory, other sub-programs commonly print output with absolute paths rooted in that directory. I think it's an improvement in general to handle it, even if https://bugs.swift.org/browse/SR-15123 is changed to make them relative again 👍
