### ISSUE TITLE
index import blocking build for xcode 14

### ISSUE THREAD

**Issue by nanwng** [bazel-ios/rules_ios#497]
Trying to build our app from generated xcodeproj in Xcode 14 beta and saw that the index-import script is blocking at the end of build. It seems like the script is not running in background anymore (Could be a new change in Xcode 14)

**Comment by jerrymarino** [comment]
Interesting, is background sub processes broken for you altogether in a post action? It seems like a FB/bug if Xcode waits for background jobs, but maybe intentional!

Also there’s an active issue to consider removing index-import, worst case we can background with another mechanism as a gap or just disable it as a stop gap..

**Comment by nanwng** [comment]
I think this seems to be fixed with later Xcode 14 beta. It works for me with Xcode 14 beta 5

**Comment by thiagohmcruz** [comment]
Cool @nanwng I'll close it for now, feel free to open a new issue if anything similar comes up!
