### ISSUE TITLE
framework macro does not seem to include cpp source files

### ISSUE THREAD

**Issue by gyfelton** [bazel-ios/rules_ios#537]
How to repro:
1. modify tests/ios/app/Cpp/hello.cpp by adding some bad text which should fail the compilation
2. run `bazel build //tests/ios/app:CppLib`, expect it to fail but it is green
3. run `bazel build //tests/ios/AppWithSelectableCopts`, expect it to fail since it depends on CppLib but it is green still
4. add `hello.h` declaring the hello method, run above steps, expect it to fail but it is still successful

**Comment by jszumski** [comment]
C++ sources are intentionally ignored: https://github.com/bazel-ios/rules_ios/blob/master/rules/library.bzl#L955

I don't believe there is a technical reason however, it's just waiting for a contribution.

**Comment by jerrymarino** [comment]
Yep it looks that test case is broken - and doesn't even compile `tests/ios/app/Cpp/hello.cpp` ATM. There's an open a PR about this: https://github.com/bazel-ios/rules_ios/pull/304 but a few pending questions on it I last checked.

I think you'd need to ensure it dedupes. PodToBUILD splits out different `objc_library` in order to give it different copts for c++ and objc - we could probably do a similar thing here as well

**Comment by gyfelton** [comment]
Gotcha! Thx for quick reply! I think we disable it for VFS, but yeah a distinct objc_library is def. the next step to try
