### ISSUE TITLE
[xcodeproj] Support Xcode 14.x new index path

### ISSUE THREAD

**Issue by mattrobmattrob** [bazel-ios/rules_ios#646]
Xcode 13: `.../DerivedData/Foo-xxx/Index/DataStore`
Xcode 14: `.../DerivedData/Foo-xxx/Index.noindex/DataStore`

Based on:

https://github.com/buildbuddy-io/rules_xcodeproj/blob/fd9180103d9917950acca12ff19959cc3e793921/xcodeproj/internal/bazel_integration_files/import_indexstores.sh#L109-L121

We can likely switch to `INDEX_DATA_STORE_DIR` to be version agnostic and it's also probably useful to pass `-undo-rules_swift-renames` to `index-import`.

**Comment by thiagohmcruz** [comment]
@mattrobmattrob I don't have a lot of context on `-undo-rules_swift-renames` but based on [this](https://cs.github.com/MobileNativeFoundation/index-import/blob/ed095ad3988a241564cbe55dc781ad463334c8d5/index-import.cpp?q=%22undo-rules_swift-renames%22#L52-L57) IIUC `Until Bazel 6.0.0` means that this is useful on older versions of Bazel only right? Meaning that since `rules_ios` is now on Bazel 6.x we don't get much from this flag?

**Comment by mattrobmattrob** [comment]
Because we have affordances like:

https://github.com/bazel-ios/rules_ios/blob/5ff9efac2bbc48ff8f78ff14c7dc83ffc2673f0f/rules/repositories.bzl#L72-L85

Seems reasonable to make it Bazel 5 & 6 capable where possible. But not sure on that specific flag, was just making sure it was recorded to try to figure it out since it's supported by `rules_xcodeproj`. 👍

**Comment by thiagohmcruz** [comment]
Resolved here: https://github.com/bazel-ios/rules_ios/pull/661 open to suggestions/feedback if I missed anything.

**Comment by mattrobmattrob** [comment]
Awesome job, @thiagohmcruz!
